### PR TITLE
Updated constant.h and readme

### PR DESCRIPTION
**Pull request by neerukulhari**
1. Updated Readme by adding -lm while running the file for Mathematics
2. Update constant.h as added extern

### CODE REVIEW

**Review by iaraota — APPROVED** [review]
Everything worked in my pc

**Comment by Stack7** [comment]
I have gor these 2 warnings:
ljmd.c:233:13: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  233 |             fscanf(fp,"%lf%lf%lf",sys.rx+i, sys.ry+i, sys.rz+i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/stack/MHPC-P2.8-project/src/ljmd.c:236:13: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  236 |             fscanf(fp,"%lf%lf%lf",sys.vx+i, sys.vy+i, sys.vz+i);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
did you get the same?

**Comment by neerukulhari** [comment]
I did not had this error while compiling, I just did with gcc ../src/*.c -I ../include -L ../include -o ljmd-serial.x -DLJMD_VERSION=1.0 -lm

**Comment by neerukulhari** [comment]
gcc ../src/*.c -I ../include -L ../include -o ljmd-serial.x -DLJMD_VERSION=1.0 -lm

**Review by Stack7 — APPROVED** [review]

**Comment by Stack7** [comment]
it works or me too!

**Pull request merged**
